### PR TITLE
Fix custom persona with empty header and footer

### PR DESCRIPTION
**Pull request by wagnerand**

### CODE REVIEW

**Comment by wagnerand** [comment]
@derinb and @mkaply could you give this a try?

**Comment by derinb** [comment]
I can confirm it is working. You may want to move the gif into content folder so root folder should be not crowded.

**Comment by wagnerand** [comment]
Have you tried that?

I don't see how that would work without further modifications as `resource://` maps to the root of the directory, not `content`.

**Comment by derinb** [comment]
I mean

`resource://persona/content/blank.gif`

**Comment by wagnerand** [comment]
Oh, yes, I can do that.

**Pull request merged**
