### PR TITLE
Custom Persona Bug Fix

### PR DESCRIPTION
**Pull request by derinb**
Custom Persona Bug Fix

### CODE REVIEW

**Comment by derinb** [comment]
Please make sure we have a Spacer.gif on AMO. Related issue:
https://github.com/mozilla/addons-server/issues/2776

**Comment by wagnerand** [comment]
What bug exactly does this PR fix? Can you please provide detailed steps to reproduce the bug?

**Comment by derinb** [comment]
Custom Personas Bug Fix
0. Install PP from AMO on fresh profile.
1. Personas Plus Toolbar Button Menu > Preferences > Enable Custom Personas
2. Personas Plus Toolbar Button Menu > Custom Persona > Edit
3. It will open up Custom Persona Editor tab.
4. Do not specify any image for Header and Footer
5. Change colors
6. Try to save it.
7. It throws error and and Persona could not be switched.

**Comment by wagnerand** [comment]
The problem is that "data" is not defined as a valid protocol for setting the `headURL`: https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/LightweightThemeManager.jsm#717 which results in that function (`_sanitizeTheme`) returning `null` which in term throws an (uncaught) error https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/LightweightThemeManager.jsm#749.

Using a `resource://` URI should work, I need to give this a try.

**Comment by wagnerand** [comment]
Yes, `resource://` works just fine for me. I'm opening another PR.

**Comment by wagnerand** [comment]
Closing in favor of https://github.com/mozilla/personas-plus/pull/21.

**Pull request closed without merging**
