### PR TITLE
Survey Thank You

### PR DESCRIPTION
**Pull request by derinb**
thankyou.html

### CODE REVIEW

**Comment by wagnerand** [comment]
Please split this PR as both commits have nothing to do with each other.

**Comment by derinb** [comment]
Do you mean creating individual PRs for each commit?

**Comment by wagnerand** [comment]
Yes.

**Comment by derinb** [comment]
But it seems it is tricky to add PR for each commit. Previous PR needs be to approved before submitting another PR.

Do you have any recommendation?

**Comment by wagnerand** [comment]
Yeah, you need to use feature branches instead of working on master. Create branches based on master and put the commits in separate branches.

I strongly recommend reading https://progit.org/

**Comment by derinb** [comment]
Thanks. I have reset this PR to only include Survey Thank you page.

**Comment by wagnerand** [comment]
Although your page looks pretty nice, we decided to go with the google forms page because we just closed the survey and want the "thank you" note to be displayed asap.
Unfortunately we cannot ship the restartless version (and this PR being based on it) yet as it is not quite ready yet.

**Comment by derinb** [comment]
OK you can close the PR.

What is not ready about restartless?

**Comment by wagnerand** [comment]
See #27. There might be more, as I haven't tested the changes yet. Please do test yourself always before you submit a PR.

**Pull request closed without merging**
