### PR TITLE
Restartless

### PR DESCRIPTION
**Pull request by derinb**
Restartless version of Personas Plus

### CODE REVIEW

**Comment by wagnerand** [comment]
Can you please include only the relevant changes to make PP restartless in this PR? Unrelated changes should go into another PR.
Also, please do not commit each file separately, it's usually fine to have one commit per PR.

Thanks.

**Comment by derinb** [comment]
Hello Andreas,

It does not contain any other changes than Restartless. First 2 is obsolete and Merge is the resource fix that you submitted yesterday.

If I delete Merge commit, things might get weird. What do you recommend?

**Comment by wagnerand** [comment]
https://github.com/mozilla/personas-plus/pull/23/commits/74faac4d34fe9f5233c04709049b9e6dd5272ec2 for example is not related to making the add-on restartless. I am sure there are other changes.

Also https://github.com/mozilla/personas-plus/pull/23/commits/e6603f6ea9cf791c13e9a2d88a460c492ba9a1a1 and https://github.com/mozilla/personas-plus/pull/23/commits/e27d30bb26288391982cdc2bb3bc186df05b3bb1 are not necessary as one reverts the other. You probably want to rebase the relevant commits onto master.

I have no idea what https://github.com/mozilla/personas-plus/pull/23/commits/70c3994faf3f9ed8b1665cebdd5f60b7e77f04c5 is about.

If you move files instead of copying them, it makes them much easier to review.

Sorry this PR is just to big to give it a meaningful review.

**Comment by wagnerand** [comment]
You might want to read http://mozweb.readthedocs.io/en/latest/reference/git_github.html

**Comment by derinb** [comment]
Andreas,

https://github.com/mozilla/personas-plus/pull/23/commits/70c3994faf3f9ed8b1665cebdd5f60b7e77f04c5
It is your commit actually:
https://github.com/mozilla/personas-plus/commit/70c3994faf3f9ed8b1665cebdd5f60b7e77f04c5

I just Synced the fork and Github created that commit.

[services.js ](https://github.com/mozilla/personas-plus/pull/23/commits/74faac4d34fe9f5233c04709049b9e6dd5272ec2) modification is 3 lines of code. Because Cu.reportError(e); is already there and does not give much information I appended console.log(e);

What do you mean by moving the file please?

I should note that modules/personas.js has different algorithm than content/personas.js. modules/personas.js has been modified to be compatible for restartless add-on. I just offered diff with content/personas.js so that you can easily see what is changed.

skin and 41 locale files are required to change. DTD files are not available for restartless add-ons.

So overall it is big but I wanted to separate commits so you can easily review what was changed by each commit.

You can safely ignore first 3 commits. Others are necessary for restartless add-on.

If you are OK with them I will create another PR.

**Comment by wagnerand** [comment]
>  It is your commit actually. You can check the diff.

Yes and because it has already been merged, there is no need to add (and remove it) again. Please rebase your changes onto master and eliminate the unnecessary commits.

> What do you mean by moving the file please?

Move means actually move a file instead of creating a duplicate by copying it.

> I just offered diff with content/personas.js so that you can easily see what is changed.

There is no need to do that. `git` will provide the diff.

> So overall it is big but I wanted to separate commits so you can easily review what was changed by each commit.

Usually, we prefer to have everything in one commit. With very large commits, sometimes it makes sense to use more than one, not in in this case though, as they are not independent. Even if so, creating one commit per file is not desired. Again, please read the _mozweb_ link above for some best practices. 

> You can safely ignore first 3 commits. Others are necessary for restartless add-on.

Please remove the first three commits then and squash the others together to just one single commit.

> If you are OK with them I will create another PR.

Please do not create another PR. Instead you can just update your current code. You can force-push afterwards and this PR will be updated automatically.

**Comment by derinb** [comment]
Sorry Andreas, this closed itself. No matter what Github client did not update my fork on Github. It did not allow to Push changes.

**Comment by wagnerand** [comment]
It's because you have to force-push.

If you delete a branch, github will automatically close the PR.

Am Freitag, 27. Mai 2016 schrieb derinb :

**Comment by derinb** [comment]
You mean from command line, right? There is only "Push" option in Github Desktop client.

Also after:

git mv extension/content/personas.js extension/modules

desktop client does not track the modifications. It assumes it as a new file. Googled about it but could not find a solution. I can first edit in content folder then modify but it might break the purpose.

Any recommendation?

**Comment by wagnerand** [comment]
Sorry, I don't use the Github Desktop client.

**Comment by derinb** [comment]
OK Andreas. I did not want to delete content/persona.js to keep things intact.  Anyway desktop client can not track moved file.

I will not move the file for the next commit. You can diff it by below, I suppose.

git diff HEAD:extension/content/personas.js extension/modules/personas.js

You may want to delete content/personas.js by yourself after my PR.

**Comment by wagnerand** [comment]
I'd prefer to have not duplicated files, same goes for the locale files. I can get the diff from git anyway.

**Comment by derinb** [comment]
personas.dtd file is also being used in customPersonaEditor.xul. So it is not possible to move it. Sorry for the trouble.

**Pull request closed without merging**
