### PR TITLE
Unhandled Promise Fixes #56

### LINKED ISSUE #56: Unhandled promise
```
A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Wed Jul 20 2016 15:15:10 GMT+0200 (CEST)
Full Message: Unix error 14 during operation remove (Bad address)
Full Stack: JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: PendingErrors.register :: line 195
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: this.PromiseWalker.completePromise :: line 718
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: Handler.prototype.process :: line 973
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: this.PromiseWalker.walkerLoop :: line 816
```

I am not entirely sure how to find the source of this.

It happens sooner or later after installing the add-on. No interaction needed.

### PR DESCRIPTION
**Pull request by derinb**
Unhandled promise fix. First checks favourites.json check before
removing it.

### CODE REVIEW

**Comment by wagnerand** [comment]
Again, if you use things like "Fixes #56" in your comment it will reference and automatically close the issue when it's getting merged.

**Comment by derinb** [comment]
Oh sorry, it was comment? I added it to the PR heading.

**Comment by wagnerand** [comment]
I don't think that will work.

**Comment by derinb** [comment]
OK next time I will add to PR comment.

**Comment by wagnerand** [comment]
I'm going to ignore the formatting issues this time. Thanks!

**Pull request merged**
