### PR TITLE
Undo Fix for First Install

### PR DESCRIPTION
**Pull request by derinb**
Fix for After pressing “Undo” button, the theme is not removed Bug

### CODE REVIEW

**Comment by wagnerand** [comment]
Can you please in your PR message use "Fixes #<ISSUE-NO" so issues automatically get closed when the PR lands? Thanks!

**Comment by wagnerand** [comment]
Looks good, thanks!

**Comment by derinb** [comment]
Does not QA need to give confirmation before accepting PR?

**Comment by wagnerand** [comment]
No the process is a bit different. Someone writes a patch, and after a reviewer approved the code and it lands, the issue gets closed automatically. QA then looks at the closed bugs (that's why I added milestones) and verifies whether they really have been fixed. If not, they get reopened.

**Pull request merged**
