### PR TITLE
 Custom Persona Data:URI Bug Fix

### PR DESCRIPTION
**Pull request by derinb**
Remove old cookie-changed observer code

### CODE REVIEW

**Comment by wagnerand** [comment]
What about `_getPersonaFromCookie` and `checkCookiesEnabled`? At least one of them is not called. The other one seems unncessary to me?

**Comment by derinb** [comment]
Yes I saw them. Especially `getPersonaFromCookie` seemed to be useful so I did not delete. Let me recheck the code base thoroughly when I have time.

I will close this PR. I need to submit a Custom Persona Bug Fix urgently. It seems you are going to release the PP as this state but Custom Persona Bug Fix should be included.

Previous versions saved data:uri is custom personas. So restartless version need to replace data:uris with resource:// uri.

Please do not release the add-on without including data:uri bug fix.

**Comment by wagnerand** [comment]
The add-on version has already been released. I did not include the restartless changes, we merely needed it for the closed survey to show up.

**Comment by wagnerand** [comment]
No need to close this PR, you can just send another one based on `master`...

**Comment by derinb** [comment]
Andreas, but custom personas bug fix need to include this commit even for restart version.

**Comment by wagnerand** [comment]
Sorry, but I have to close this PR as it changed completely. Please open a new PR and don't change its purpose along the way.

**Pull request closed without merging**
