### PR TITLE
Localisation Support

### PR DESCRIPTION
**Pull request by derinb**
This adds localisation strings for background image size restriction
warning prompt and shutdown theme removal warning prompt.

### CODE REVIEW

**Comment by derinb** [comment]
Hi Jorge,

Andreas needs to review this because he downloads the locale files from Babelzilla.

Thanks

**Comment by derinb** [comment]
Hello Anrdeas,

Welcome back. Just a reminder in your pilled inbox emails.

**Comment by wagnerand** [comment]
I am unable to get babelzilla to output the files that I need, so I am not sure whether we can keep using it. The interface is quite broken and talking to the developer a couple of weeks ago did not help.

**Comment by derinb** [comment]
Should I close this?

**Comment by wagnerand** [comment]
I honestly don't know what to do here.

**Comment by wagnerand** [comment]
I am considering ditching babelzilla, maybe for now we should copy the english strings to all locales.

**Comment by derinb** [comment]
Appended strings for all languages. 

Thanks

**Comment by wagnerand** [comment]
Looks good, thank you!

**Pull request merged**
